### ISSUE TITLE
using v2 sharedhelper to merge targets

### ISSUE THREAD

**Issue by swaros** [swaros/contxt#147]
V2 do not support right n the following require configuration 

```yaml
config:
  require:
      - swaros/ctx-docker
 ```

this means the required context file is merged with the content from the current contxt file.
