### ISSUE TITLE
Variables not replaced by nested macro SET

### ISSUE THREAD

**Issue by swaros** [swaros/contxt#185]
**Describe the bug**
variables not parsed in any case like V1 is doing.

**To Reproduce**
create contxt file like so

```yaml
config:
  imports:
     - ctx-default.yml local-config
     
task:
  - id: local-config
    require:
      system: linux
      exists:
        - ${USER}.local.json
    script:
      - echo "loading local config file from user ${USER}.local.json"
      - "#@import-json-exec local-config cat ${USER}.local.json"

  - id: build-base-image
    needs:
      - local-config
    script:
      - echo "testing vars"
      - "#@set RUNCMD --build-arg CMP_KEYID=${local-config:HIDDEN.CMP_KEYID}"
      - "#@set RUNCMD ${RUNCMD} --build-arg CMP_ACID=${local-config:HIDDEN.CMP_ACID}"
      - "#@set RUNCMD ${RUNCMD} --build-arg LICENCE_KEY=${local-config:HIDDEN.LICENCE_KEY}"
      - echo "${RUNCMD}"      
```

also create an json file with the needed keys in
named with  ${USER}.local.json
```json
{
  "HIDDEN": {
    "CMP_KEYID": "0815",
    "CMP_ACID": "thisisAnExample",
    "LICENCE_KEY": "andthisisalsonotanrealkey"
  }
}

```
watch what is happen.
also compare with v1 what is doing well.

**Expected behavior**
variables have to replaced with the content any time. at least like v1 is doing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux
