### ISSUE TITLE
shared task not updateable after clone 

### ISSUE THREAD

**Issue by swaros** [swaros/contxt#33]
https://github.com/swaros/contxt/blob/f4ac739ceade2551dc7f135b059cc3f33b8cffd6/context/cmdhandle/shareduse.go#L114

after cloning a shared task, like so:

````yaml
config:
  require:
     - swaros/ctx-gh@v0.0.1
  ````

the task version file can not be found.

first: this have to  be solved. (creation of the task file)
and second: even if the version info is missing. it should possible to recover automatically (check for .git exists or something else)
