### ISSUE TITLE
Contxt project infos

### ISSUE THREAD

**Issue by swaros** [swaros/contxt#41]
**Is your feature request related to a problem? Please describe.**
some projects depends on some sup-projects they are hosted in different repositories. so  anyone can have different locations locally.
if some task depends on other projects it is required to know the locations.

contxt iteself have this information already, but this is not well used in the contxt tasks definition

**Describe the solution you'd like**
 any .contxt.yml should have a seperate block thats descripes the "contxt".

````yaml
context:
  workspace: name-of-workspace
  aliases:
    - website
    - php
```` 

this can be used for 
 - scanning new checkouts and create workspaceses and assigned paths
 - as alias for **workingdir** so just the workspace and the target path can be used

in detail:
a new command **scan** (for example) scan from a given path and reads any .contxt.yml file they found. if the workspace section exists, they will used to check if the workspace exists, create them if not and add the path....or if they exists, check if the path is already stored, and if not, store them as well.

in the task definition a new entry called **context** they have the following structure

```yaml
 - id: task
   context:
      workspace: lima     # optional
      find: website    # required
```
this would work like the **workingdir** option and change the directory for this task depending the workspace and the path they can be find.
important: if no path matches, the whole process have to fail to make sure no execution is done on a wrong path.

**Describe alternatives you've considered**

**Additional context**
