### ISSUE TITLE
listener - action - scripts runs multiple

### ISSUE THREAD

**Issue by swaros** [swaros/contxt#60]
**Describe the bug**
the trigger OnOutContains seems running mutliple times.
this happens by using the script section.
target not tested but should be investigated.

**To Reproduce**
here an example 
```
   - id: minikube  
    script:
      - echo "starting ${mkname} @ ${mkbin}"
    next:
      - minikube-check


  - id: minikube-check
    options:
      invisible: true
      ignoreCmdError: true 
    require:
      variables:
        mkbin: "*"
    script:
      - ${mkname} status # if not running it will exists with exit code 1
    listener:
      - trigger:
          onoutContains:
            - Stopped
        action:
         script:
           - ${mkname} start
```

![grafik](https://user-images.githubusercontent.com/5437750/197949109-1cc2033b-f913-4061-b1f1-902233127915.png)

**Expected behavior**
the task `${mkname} start` in the listener should run once. 

**Desktop (please complete the following information):**
 - arch
